ALTER SESSION SET CONTAINER = XEPDB1;
GRANT CREATE SESSION TO RENDER_AI;
GRANT CREATE TABLE TO RENDER_AI;
GRANT CREATE SEQUENCE TO RENDER_AI;
GRANT CREATE VIEW TO RENDER_AI;
GRANT UNLIMITED TABLESPACE TO RENDER_AI;
EXIT;
